from social_media_downloader_easy.downloader.instagram.consts import (
    IGMEDIA_DOWNLOAD_INSTAGRAM_VIDEO_HMAC_SECRET,
    IGMEDIA_DOWNLOAD_INSTAGRAM_VIDEO_ENDPOINT_URL
)
from social_media_downloader_easy.downloader.instagram.regex import (
    InstagramVideoLinkRegularExpression
)
from social_media_downloader_easy.platform.instagram.dataclasses import (
    InstagramPostUrl
)

import base64
import hashlib
import hmac
import json
import re
import time
import uuid


IGMEDIA_BACKEND_HOST = 'https://api.ig.media'
IGMEDIA_VERSION = '0.1.62'


# ---------------------------------------------------------------------------
# Visitor / CSRF / browser fingerprint state
# ---------------------------------------------------------------------------

_IGMEDIA_VISITOR_ID = None
_IGMEDIA_VISITOR_COUNT = 0
_IGMEDIA_VISITOR_TIMESTAMP = None

_IGMEDIA_CSRF_TOKEN = None
_IGMEDIA_CSRF_TOKEN_EXPIRES_AT = 0

_IGMEDIA_BROWSER_FP = None


# ---------------------------------------------------------------------------
# JavaScript compatibility helpers
# ---------------------------------------------------------------------------

def _js_imul(
    a: int,
    b: int
) -> int:
    """
    Python equivalent of JavaScript Math.imul().
    """

    result = (a & 0xFFFFFFFF) * (b & 0xFFFFFFFF)
    result &= 0xFFFFFFFF

    if result >= 0x80000000:
        result -= 0x100000000

    return result


def _js_char_codes(
    value: str
):
    """
    JavaScript String.charCodeAt() works with UTF-16 code units,
    rather than Python Unicode code points.
    """

    encoded = value.encode('utf-16-le')

    for index in range(0, len(encoded), 2):
        yield int.from_bytes(
            encoded[index:index + 2],
            byteorder='little'
        )


def _browser_fingerprint_hash(
    value: str
) -> str:
    """
    Exact implementation of the `ne()` function used by ig.media.
    """

    R = 3735928559
    f = 1103547991

    for char_code in _js_char_codes(value):
        R = _js_imul(
            R ^ char_code,
            2654435761
        )

        f = _js_imul(
            f ^ char_code,
            1597334677
        )

    R = (
        _js_imul(
            R ^ ((R & 0xFFFFFFFF) >> 16),
            2246822507
        )
        ^
        _js_imul(
            f ^ ((f & 0xFFFFFFFF) >> 13),
            3266489909
        )
    )

    f = (
        _js_imul(
            f ^ ((f & 0xFFFFFFFF) >> 16),
            2246822507
        )
        ^
        _js_imul(
            R ^ ((R & 0xFFFFFFFF) >> 13),
            3266489909
        )
    )

    R_unsigned = R & 0xFFFFFFFF
    f_unsigned = f & 0xFFFFFFFF

    value_number = (
        4294967296 * (2097151 & f_unsigned)
        + R_unsigned
    )

    return format(
        value_number,
        'x'
    ).zfill(16)


def _generate_browser_fingerprint() -> str:
    """
    Recreates the browser fingerprint generated by ig.media.

    The original browser implementation uses:

        screen.width
        screen.height
        screen.colorDepth
        timezone offset
        navigator.platform
        navigator.language
        navigator.hardwareConcurrency
        canvas.toDataURL()

    The canvas rendering cannot be reproduced exactly from pure Python,
    so for now we reproduce the rest of the fingerprint and use the
    same hashing algorithm.
    """

    global _IGMEDIA_BROWSER_FP

    if _IGMEDIA_BROWSER_FP is not None:
        return _IGMEDIA_BROWSER_FP

    values = [
        '1920x1080x24',
        'tz:-480',
        'p:Win32',
        'l:en-US',
        'c:8'
    ]

    # The browser adds:
    #
    # cv:${canvas.toDataURL().slice(-32)}
    #
    # We intentionally leave it out for this first test.
    #
    # Once we know the server requires the exact canvas fingerprint,
    # we can obtain it from Chrome/Playwright and add it here.

    fingerprint_source = '|'.join(values)

    _IGMEDIA_BROWSER_FP = _browser_fingerprint_hash(
        fingerprint_source
    )

    return _IGMEDIA_BROWSER_FP


# ---------------------------------------------------------------------------
# Visitor token
# ---------------------------------------------------------------------------

def _to_base36(
    value: int
) -> str:
    """
    JavaScript-compatible integer -> base36.
    """

    if value == 0:
        return '0'

    alphabet = '0123456789abcdefghijklmnopqrstuvwxyz'

    result = ''

    while value:
        value, remainder = divmod(
            value,
            36
        )

        result = alphabet[remainder] + result

    return result


def _generate_visitor_id() -> str:
    """
    Equivalent to the JavaScript Yi() function.
    """

    alphabet = 'abcdefghijklmnopqrstuvwxyz0123456789'

    random_part = ''.join(
        alphabet[
            int(
                __import__('random').random()
                * len(alphabet)
            )
        ]
        for _ in range(16)
    )

    timestamp = int(
        time.time() * 1000
    )

    return (
        f'vid_{_to_base36(timestamp)}_{random_part}'
    )


def _get_visitor_token() -> str:
    """
    Equivalent to the JavaScript Zi() function.

    The frontend keeps this information in localStorage/cookie.
    We keep it at module level so it survives multiple downloads
    during the lifetime of this Python process.
    """

    global _IGMEDIA_VISITOR_ID
    global _IGMEDIA_VISITOR_COUNT
    global _IGMEDIA_VISITOR_TIMESTAMP

    if _IGMEDIA_VISITOR_ID is None:
        _IGMEDIA_VISITOR_ID = _generate_visitor_id()
        _IGMEDIA_VISITOR_COUNT = 0
        _IGMEDIA_VISITOR_TIMESTAMP = int(
            time.time() * 1000
        )

    visitor = {
        'v': _IGMEDIA_VISITOR_ID,
        'c': _IGMEDIA_VISITOR_COUNT + 1,
        't': _IGMEDIA_VISITOR_TIMESTAMP,
        'r': ''
    }

    visitor_json = json.dumps(
        visitor,
        ensure_ascii=False,
        separators=(',', ':')
    )

    return base64.b64encode(
        visitor_json.encode('utf-8')
    ).decode('ascii')


def _increment_visitor_counter() -> None:
    """
    Equivalent to the JavaScript Ji() function.
    """

    global _IGMEDIA_VISITOR_COUNT

    _IGMEDIA_VISITOR_COUNT += 1


# ---------------------------------------------------------------------------
# CSRF
# ---------------------------------------------------------------------------

async def _get_csrf_token(
    social_media_downloader: 'SocialMediaDownloader'
) -> str:
    """
    Obtain the CSRF token from:

        https://api.ig.media/api/client-config

    The frontend caches this token for 10 minutes.
    """

    global _IGMEDIA_CSRF_TOKEN
    global _IGMEDIA_CSRF_TOKEN_EXPIRES_AT

    now = int(
        time.time() * 1000
    )

    # Frontend:

    # const oe = 10 * 60 * 1e3;
    # const ie = 60 * 1e3;
    #
    # if (D0 && ir && Date.now() < ir - ie)
    #     return D0;

    if (
        _IGMEDIA_CSRF_TOKEN
        and now < _IGMEDIA_CSRF_TOKEN_EXPIRES_AT - 60_000
    ):
        return _IGMEDIA_CSRF_TOKEN

    browser_fingerprint = _generate_browser_fingerprint()

    headers = {}

    if browser_fingerprint:
        headers['x-client-id'] = browser_fingerprint

    # print("CSRF 1: requesting client-config")

    response = await social_media_downloader._file_downloader.client.get.complete(
        url=f'{IGMEDIA_BACKEND_HOST}/api/client-config',
        headers=headers
    )

    # print(f"CSRF 2: response = {response}")

    # print("CSRF 3: reading JSON")

    await response.aread()

    # print("CSRF 4: JSON read")

    if not response.is_success:
        raise RuntimeError(
            'Could not obtain ig.media CSRF token. '
            f'HTTP status: {response.status_code}'
        )

    try:
        json_response = response.json()
    except Exception as exception:
        raise RuntimeError(
            'Could not parse ig.media client-config response.'
        ) from exception

    token = json_response.get('token')

    if not token:
        raise RuntimeError(
            'ig.media client-config response did not contain a token.'
        )

    _IGMEDIA_CSRF_TOKEN = token

    _IGMEDIA_CSRF_TOKEN_EXPIRES_AT = (
        now + 10 * 60 * 1000
    )

    return token


# ---------------------------------------------------------------------------
# Request
# ---------------------------------------------------------------------------

async def _get_request_headers_and_body(
    social_media_downloader: 'SocialMediaDownloader',
    url: str
) -> tuple[dict, str]:
    """
    Get the headers and body needed to make the request to ig.media.

    This reproduces the request made by the current ig.media frontend.
    """

    # -----------------------------------------------------------------------
    # 1. Session ID
    # -----------------------------------------------------------------------

    session_id = str(
        uuid.uuid4()
    )

    # -----------------------------------------------------------------------
    # 2. Visitor token
    # -----------------------------------------------------------------------

    visitor_token = _get_visitor_token()

    # -----------------------------------------------------------------------
    # 3. Body
    # -----------------------------------------------------------------------

    payload = {
        'url': url,
        'sessionId': session_id,
        'version': IGMEDIA_VERSION,
        '_vt': visitor_token
    }

    # IMPORTANT:
    #
    # This exact string is what is signed by HMAC and sent as the request
    # body.
    #
    body = json.dumps(
        payload,
        ensure_ascii=False,
        separators=(',', ':')
    )

    # -----------------------------------------------------------------------
    # 4. Timestamp
    # -----------------------------------------------------------------------

    timestamp = str(
        int(
            time.time() * 1000
        )
    )

    # -----------------------------------------------------------------------
    # 5. HMAC
    # -----------------------------------------------------------------------

    message = (
        f'{timestamp}.{body}'
    )

    signature = hmac.new(
        IGMEDIA_DOWNLOAD_INSTAGRAM_VIDEO_HMAC_SECRET.encode('utf-8'),
        message.encode('utf-8'),
        hashlib.sha256
    ).hexdigest()

    # -----------------------------------------------------------------------
    # 6. CSRF
    # -----------------------------------------------------------------------

    csrf_token = await _get_csrf_token(
        social_media_downloader
    )

    # -----------------------------------------------------------------------
    # 7. Browser fingerprint
    # -----------------------------------------------------------------------

    browser_fingerprint = _generate_browser_fingerprint()

    # -----------------------------------------------------------------------
    # 8. Headers
    # -----------------------------------------------------------------------

    headers = {
        'Content-Type': 'application/json',

        'x-hmac-signature': signature,

        'x-timestamp': timestamp,

        'x-csrf-token': csrf_token,

        'x-browser-fp': browser_fingerprint,

        'sec-ch-ua-platform': '"Windows"',

        'Referer': 'https://www.ig.media/',

        'sec-ch-ua': (
            '"Chromium";v="148", '
            '"Google Chrome";v="148", '
            '"Not/A)Brand";v="99"'
        ),

        'sec-ch-ua-mobile': '?0',

        'User-Agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/148.0.0.0 Safari/537.36'
        )
    }

    return headers, body


class _InstagramDownloader:
    """
    *For internal use only*

    Shortcut to the functionality related to
    Instagram.
    """

    def __init__(
        self,
        social_media_downloader: 'SocialMediaDownloader'
    ):
        self._social_media_downloader: 'SocialMediaDownloader' = (
            social_media_downloader
        )
        """
        *For internal use only*

        The reference to the `SocialMediaDownloader` parent.
        """


    async def get_download_url_new(
        self,
        url: str
    ) -> str:

        # print("1. Starting get_download_url_new")

        url = InstagramPostUrl(url).reel_url

        # print(f"2. Normalized URL: {url}")

        headers, body = await _get_request_headers_and_body(
            self._social_media_downloader,
            url
        )

        # print("3. Headers/body ready")

        with self._social_media_downloader._file_downloader.follow_redirects(True):

            # print("4. Starting instagram-media request")

            async with await self._social_media_downloader._file_downloader.client.post.stream(
                url=IGMEDIA_DOWNLOAD_INSTAGRAM_VIDEO_ENDPOINT_URL,
                headers=headers,
                content=body
            ) as response:

                # print(f"5. instagram-media response: {response}")

                await response.aread()

                # print("6. instagram-media body read")

                json_response = response.json()

                # print("7. JSON decoded")

                video_url = json_response['elements'][0]['url']

                # print(f"8. Video URL obtained: {video_url}")

                return video_url


    """
    TODO: This must be removed if the new method
    is working, because the new one is accepting
    and managing the urls properly, and this old
    method is limited and raising exceptions when
    it shouldn't.
    """

    async def get_download_url(
        self,
        # TODO: Accept IDs also
        url: str
    ) -> str:
        """
        Download the Facebook video from the given `url`
        and save it locally with the `output_filename`
        file name provided.

        The `url` must be like this:
        - https://www.instagram.com/reel/DHQf6RmMFtf/?igsh=ZBDzeTA4cWkwbW4w

        The urls below are not working for this method.
        - https://www.instagram.com/share/DHtsmGHTOn4
        - https://www.instagram.com/reels/DHtsmGHTOn4/
        - https://www.instagram.com/p/DHtsmGHTOn4/

        This method will call an specific endpoint to
        obtain the result.
        """

        if not InstagramVideoLinkRegularExpression.is_valid_url(url):
            raise Exception(
                f'The "url" provided is not a valid Instagram url: {url}'
            )

        # Valid for this method
        VALID_URL_REGEX = [
            InstagramVideoLinkRegularExpression.INSTAGRAM_REEL_REGEX.value,
            InstagramVideoLinkRegularExpression.INSTAGRAM_POST_REGEX.value
        ]

        if not any(
            re.fullmatch(regex, url)
            for regex in VALID_URL_REGEX
        ):
            raise ValueError(
                f'URL not accepted for this way of downloading: {url}'
            )

        # print("1. Starting get_download_url")

        headers, body = await _get_request_headers_and_body(
            self._social_media_downloader,
            url
        )

        # print(f"2. Normalized URL: {url}")

        # print("4. Starting instagram-media request")

        with self._social_media_downloader._file_downloader.follow_redirects(True):
            async with await self._social_media_downloader._file_downloader.client.post.stream(
                url=IGMEDIA_DOWNLOAD_INSTAGRAM_VIDEO_ENDPOINT_URL,
                headers=headers,
                content=body
            ) as response:
                # print(f"5. instagram-media response: {response}")

                await response.aread()

                # print("6. instagram-media body read")

                json_response = response.json()

                # print("7. JSON decoded")

                if not response.is_success:
                    error = json_response.get(
                        'error',
                        'Unknown ig.media error'
                    )

                    raise RuntimeError(
                        f'ig.media returned HTTP '
                        f'{response.status_code}: {error}'
                    )

                video_url = json_response['elements'][0]['url']

                # print(f"8. Video URL obtained: {video_url}")

                _increment_visitor_counter()

                return video_url